version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task -l

  all:
    desc: Run all tasks
    cmds:
      - rm -rf build
      - go build -o build/mutercim ./cmd/mutercim
      - go test ./...
      - go vet ./...
      - golangci-lint run

  build:
    desc: Build for the current platform
    cmds:
      - go build -o build/mutercim ./cmd/mutercim

  install:
    desc: Install mutercim to GOPATH/bin
    cmds:
      - go install ./cmd/mutercim

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  docker-xelatex:
    desc: Build the XeLaTeX Docker image
    cmds:
      - docker build -t mutercim/xelatex docker/xelatex/
