package renderer

import (
	"context"
	"fmt"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/mmdemirbas/mutercim/internal/lang"
	"github.com/mmdemirbas/mutercim/internal/model"
)

// TypstRenderer produces Typst (.typ) source from translated region
// pages. Typst is a parallel alternative to the XeLaTeX renderer:
// faster, single ~40 MB binary instead of TeX Live (~4 GB), and Typst
// 0.14 fixed the RTL crash plus added kashida-based justification
// (the two blockers identified in pre-implementation research). Phase
// 0 spike confirmed clean rendering of Anfas-shape Arabic content.
type TypstRenderer struct {
	// Lang is the output language code (e.g. "ar", "tr", "en"). When
	// the language profile declares dir=rtl, the renderer wraps body
	// text in a #set text(dir: rtl) context.
	Lang string
}

// Extension returns ".typ".
func (r *TypstRenderer) Extension() string { return ".typ" }

// RenderPage renders a single translated region page as Typst content.
// Returned content is INSIDE the body — the page assembly (preamble,
// font config, page size, header) is RenderBook's responsibility.
func (r *TypstRenderer) RenderPage(page *model.TranslatedRegionPage) string {
	var b strings.Builder
	regionMap := buildRegionIDMap(page.Regions)
	for _, id := range page.ReadingOrder {
		region := regionMap[id]
		if region == nil {
			continue
		}
		switch region.Type {
		case model.RegionTypeHeader:
			if region.TranslatedText == "" {
				continue
			}
			fmt.Fprintf(&b, "= %s\n\n", typstEscape(region.TranslatedText))
		case model.RegionTypeEntry:
			if region.TranslatedText == "" {
				continue
			}
			fmt.Fprintf(&b, "%s\n\n", typstEscape(region.TranslatedText))
		case model.RegionTypeFootnote:
			if region.TranslatedText == "" {
				continue
			}
			fmt.Fprintf(&b, "#footnote[%s]\n\n", typstEscape(region.TranslatedText))
		case model.RegionTypeSeparator:
			b.WriteString("#line(length: 100%, stroke: 0.4pt)\n\n")
		case model.RegionTypePageNumber:
			// Suppressed; Typst's #counter(page) handles numbering.
		}
	}
	return b.String()
}

// RenderBook renders the full document including preamble, font
// configuration, page setup, and per-page bodies. The Lang profile's
// rendering hints drive the dir=rtl wrap when applicable.
func (r *TypstRenderer) RenderBook(pages []*model.TranslatedRegionPage) string {
	var b strings.Builder

	// Preamble: page size, font, paragraph settings. The font fallback
	// chain mirrors what hadis-book uses in production for Arabic
	// content. When Shaikh Hamdullah Mushaf is not on the user's font
	// path, Typst falls back to system fonts.
	hints := lang.Get(r.Lang).RenderingHints()
	rtl := hints["dir"] == "rtl"

	b.WriteString("// Generated by mutercim — Typst output\n")
	b.WriteString("#set page(paper: \"a4\", margin: 2.5cm, numbering: \"1\")\n")
	b.WriteString("#set text(\n")
	if rtl {
		b.WriteString("  font: (\"Shaikh Hamdullah Mushaf\", \"Amiri\", \"Geeza Pro\", \"Noto Naskh Arabic\"),\n")
		b.WriteString("  size: 13pt,\n")
		fmt.Fprintf(&b, "  lang: %q,\n", r.Lang)
		b.WriteString("  fallback: true,\n")
	} else {
		b.WriteString("  font: (\"Alegreya\", \"New Computer Modern\", \"Helvetica\"),\n")
		b.WriteString("  size: 12pt,\n")
		fmt.Fprintf(&b, "  lang: %q,\n", r.Lang)
	}
	b.WriteString(")\n")
	b.WriteString("#set par(justify: true, leading: 0.7em)\n\n")

	for i, page := range pages {
		if i > 0 {
			b.WriteString("#pagebreak()\n\n")
		}
		fmt.Fprintf(&b, "// === Source page %d ===\n", page.PageNumber)
		body := r.RenderPage(page)
		if rtl {
			// Wrap each page body in an explicit RTL context so the
			// preamble dir setting doesn't have to be global (lets us
			// nest LTR runs cleanly when needed).
			b.WriteString("#text(dir: rtl)[\n")
			b.WriteString(body)
			b.WriteString("]\n\n")
		} else {
			b.WriteString(body)
			b.WriteString("\n")
		}
	}
	return b.String()
}

// typstEscape escapes the small set of Typst metacharacters in text
// that we forward verbatim from region text. Typst's syntax is much
// less escape-heavy than LaTeX: only #, @, $, and a few brackets
// trigger markup interpretation, and only at line/word start in most
// cases. We escape conservatively.
//
// We deliberately do NOT escape Arabic characters or diacritics —
// Typst handles them natively.
func typstEscape(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`,
		"#", `\#`,
		`@`, `\@`,
		`$`, `\$`,
		`<`, `\<`,
	)
	return r.Replace(s)
}

// CompileTypstPDF runs `typst compile <file>.typ` and writes the
// matching .pdf next to it. Returns a clear error when typst is not
// on PATH so the caller can fall back to XeLaTeX or skip.
//
// fontPath is optional; when non-empty, passed as --font-path so
// bundled fonts (e.g. hadis-book/fonts/) override system fonts.
func CompileTypstPDF(ctx context.Context, typPath, fontPath string) error {
	if _, err := exec.LookPath("typst"); err != nil {
		return fmt.Errorf("typst is required but not on PATH — install with 'brew install typst' or see https://typst.app")
	}
	args := []string{"compile"}
	if fontPath != "" {
		args = append(args, "--font-path", fontPath)
	}
	absTyp, err := filepath.Abs(typPath)
	if err != nil {
		return fmt.Errorf("resolve typst input path: %w", err)
	}
	args = append(args, absTyp)

	out, err := exec.CommandContext(ctx, "typst", args...).CombinedOutput() //nolint:gosec // G204: typst is a fixed binary on PATH; args are internal
	if err != nil {
		return fmt.Errorf("typst compile failed: %w\noutput: %s", err, truncateOutput(string(out), 500))
	}
	return nil
}
